version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - sam --version

  build:
    commands:
      - sam build --template template.yaml --parameter-overrides ParameterKey="Stage",ParameterValue="dev" ParameterKey="ProjectName",ParameterValue="mebweb"
      - echo $CODEBUILD_INITIATOR
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-dev$"; then
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities=CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides ParameterKey="Stage",ParameterValue="dev" ParameterKey="ProjectName",ParameterValue="mebweb" --stack-name sam-deploy-development
        fi;
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-stage$"; then
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities=CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides ParameterKey=Stage,ParameterValue=stage ParameterKey="ProjectName",ParameterValue="mebweb" --stack-name sam-deploy-staging
        fi;  
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-prod$"; then
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --capabilities=CAPABILITY_NAMED_IAM --disable-rollback --parameter-overrides ParameterKey=Stage,ParameterValue=prod --stack-name sam-deploy-production
        fi;