AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
  
  ProjectName:
    Type: String

Resources:
  ReadEnvFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub read-env-${ProjectName}-${Stage}
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/*"
